[package]
name = "autofxembed"
version = "0.1.0"
edition = "2021"
rust-version = "1.89"

[dependencies]
arboard = { version = "3", default-features = false }
dirs = "5"

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_DataExchange",
    "Win32_System_Registry",
    "Win32_System_LibraryLoader",
    "Win32_UI_Shell",
    "Win32_Graphics_Gdi",
] }

[target.'cfg(target_os = "linux")'.dependencies]
ksni = { version = "0.3", features = ["blocking"] }
x11rb = { version = "0.13", default-features = false, features = ["xfixes"] }
wl-clipboard-rs = "0.9"
arboard = { version = "3", default-features = false, features = ["wayland-data-control"] }
wayland-client = "0.31"
wayland-protocols = { version = "0.32", features = ["client", "staging"] }
wayland-protocols-wlr = { version = "0.3", features = ["client"] }


[build-dependencies]
embed-resource = "2"
image = { version = "0.25", default-features = false, features = ["ico"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = "symbols"
panic = "abort"
