pub mod autostart;
pub mod clipboard;
pub mod config;
pub mod dialog;
pub mod history;
pub mod monitor;
pub mod panel;
pub mod transform;
pub mod tray;
pub mod update;
#[cfg(target_os = "linux")]
pub(crate) mod wayland_watch;
